import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { MainProvider } from "./context/ContextAPI";
import { DebounceProvider } from "./context/Debounce";
import { ThemeToggleProvider } from "./context/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainProvider>
          <DebounceProvider>
            <ThemeToggleProvider>
              {children}
              </ThemeToggleProvider>
            </DebounceProvider>
        </MainProvider>
      </body>
    </html>
  );
}
